### ISSUE TITLE
The latest adapters.py has not been pushed

### ISSUE THREAD

**Issue by tomo-wb** [yuzu-ai/japanese-llm-ranking#9]
In this commit (https://github.com/yuzu-ai/japanese-llm-ranking/commit/a3942487c7594503f482e3bf4eddbe61c3a4bbcb), there is a change in jrank/get_model_qa.py where it now imports JapaneseStableLMAdapter from adapters, but it seems that adapters.py hasn't been updated. 
Would it be possible to upload the latest adapters.py?

**Comment by passaglia** [comment]
Thank you for pointing this out, it should be fixed now!
